## Day 3 - Part 1)


1. Load in text data and format properly into a 2d array
2. Calculate most common value (1 or 0) per column
3. Calc most common (and least common) values per column and concat into a binary number e.g. 1011
4. Convert binary into decimal

In [42]:
import numpy as np
from io import StringIO

### Declare Functions

In [165]:
def load_txt_array(txt_path):
    with open(txt_path) as f:
        txt_str = f.read()   
    text_w_spaces =' '.join(txt_str)
    return np.loadtxt(fname=StringIO(text_w_spaces), dtype=np.int64)
    
def calc_max_min_arrays(array):
    max_val = []
    min_val = []
    for n in range(0, array.shape[1]):
        vals, counts = np.unique(array[:, n], return_counts=True) #iterates through each col

        max_idx = np.where(counts == np.amax(counts))[0][0]
        max_val.append(vals[max_idx])

        min_idx = np.where(counts == np.amin(counts))[0][0]
        min_val.append(vals[min_idx])

    max_val_arr = np.asarray(max_val) #convert to array
    min_val_arr = np.asarray(min_val)
    
    return max_val_arr, min_val_arr


def convert_bin_dec(array):
    decimal = 0
    n = array.shape[0] -1  # total no. of chars
    
    for i in range(0, n+1): # range chops off last no. only iterate thru 4 no. w/o  n+1
        # could write this in a recursive fn
        decimal += array[i] * 2**(n-i)
    
    return decimal

### Example


In [64]:
# no delimiters in data means numpy doesn't load in data correctly
# e.g. is read in as 1011, instead of 1,0,1,1; need to add spaces

with open("test_input.txt") as f:
    txt_str = f.read()   

In [65]:
txt_str

'00100\n11110\n10110\n10111\n10101\n01111\n00111\n11100\n10000\n11001\n00010\n01010'

In [67]:
text_w_spaces =' '.join(txt_str) # adds a space after each char

In [68]:
text_w_spaces

'0 0 1 0 0 \n 1 1 1 1 0 \n 1 0 1 1 0 \n 1 0 1 1 1 \n 1 0 1 0 1 \n 0 1 1 1 1 \n 0 0 1 1 1 \n 1 1 1 0 0 \n 1 0 0 0 0 \n 1 1 0 0 1 \n 0 0 0 1 0 \n 0 1 0 1 0'

In [76]:
test_data = np.loadtxt(fname=StringIO(text_w_spaces), dtype=np.int64)
test_data

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0]], dtype=int64)

In [167]:
test_data = load_txt_array("test_input.txt") # confirming fn works
test_data

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0]], dtype=int64)

In [169]:
test_data.shape

(12, 5)

In [170]:
test_data.shape[1]

5

In [185]:
test_gamma, test_epsilon = calc_max_min_arrays(test_data)
print(test_gamma, test_epsilon)

[1 0 1 1 0] [0 1 0 0 1]


In [186]:
print(convert_bin_dec(test_gamma), ',', convert_bin_dec(test_epsilon))

22 , 9


### Actual

In [179]:
data = load_txt_array("input.txt")

In [180]:
data

array([[1, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [1, 1, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [181]:
data.shape

(1000, 12)

In [187]:
gamma, epsilon = calc_max_min_arrays(data)


In [188]:
gamma, epsilon

(array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0], dtype=int64),
 array([1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1], dtype=int64))

In [189]:
print(convert_bin_dec(gamma),  convert_bin_dec(epsilon))

802 3293


In [161]:
802 * 3293

2640986

# Part 2)